### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by jasonrbriggs** [matkuki/python3#1]
Tested a simple example and got the following error when compiling:

```
python3.nim(1577, 16) Error: undeclared identifier: 'PyUCS4'
```

Looking at the definition of PyUCS4 I can see the issue if I run this:

```nim
echo sizeof(int).`$`
echo sizeof(clong).`$`
```

Which outputs:

```
8
8
```

**Comment by jasonrbriggs** [comment]
Addendum: I got it to work (compile) locally by hacking the following:

```
@@ -1563,7 +1563,7 @@ type
   PyUCS1* = cuchar
   PyUCS2* = cushort
 
-when sizeof(int) == 4: 
+when sizeof(cuint) == 4: 
```

Then hit a further problem because I only have python3.6 installed.  In the end, the following changes got the example to run at least:

```
@@ -17,12 +17,12 @@ import
 
 # Define the library filename
 when defined(windows): 
-  const libraryString = "python(35|34|33|32|31|3).dll"
+  const libraryString = "python(36|35|34|33|32|31|3).dll"
 elif defined(macosx):
-  const libraryString = "libpython(3.5|3.4|3.3|3.2|3.1|3).dylib"
+  const libraryString = "libpython(3.6|3.5|3.4|3.3|3.2|3.1|3).dylib"
 else: 
-  const versionString = ".1"
-  const libraryString = "libpython(3.5|3.4|3.3|3.2|3.1|3).so" & versionString
+  const versionString = ".1.0"
+  const libraryString = "libpython(3.6m|3.6|3.5|3.4|3.3|3.2|3.1|3).so" & versionString
```
Not entirely sure about the versionString - whether that's specific to Arch linux and on other distros it's .1? (I definitely have "libpython3.6m.so.1.0" in /usr/lib)

**Comment by matkuki** [comment]
Hey @jasonrbriggs ,

Thanks, I will add your changes.
Which example are you testing?

**Comment by jasonrbriggs** [comment]
I copied this...

```python
import python3
let pythonString = "import sys\nprint(sys.version)"
setProgramName("get Python3 version string")
initialize()
if runSimpleString(pythonString) == -1:
    echo("Exception occured in Python script!")
finalize()
```

...from here: https://github.com/matkuki/python3/blob/master/examples/examples.nim to test it out.

**Comment by matkuki** [comment]
Huh, weird. Just tried it on Windows Vista 64-bit with Python3.6 36-bit / Nim 0.16.1 64-bit and it works without any changes to PyUCS4.
Will add your fix with the **defined(posix)** flag.

Since you're the first person to raise an issue, do you have time to test a Python 3 extension written in Nim on Linux? I have an extension that works on windows but have trouble getting it to work on Linux. If you have time I can give you the files or you can look at the forum post here:
https://forum.nim-lang.org/t/2927

**Comment by matkuki** [comment]
Updated the library. Can you please test the new code?

Thanks,
Matic

**Comment by jasonrbriggs** [comment]
Tested.  Confirmed that it works fine, thanks.

In terms of the Py3 extension, are you trying to import nim code into python?  So you're compiling to a DLL?  If so, I haven't yet figured out what voodoo magic is required to build a .so on unix (let me know how you're compiling and I can try that).

**Comment by matkuki** [comment]
Yes, a Python 3 module in Nim.
I put the three files into a gist here: https://gist.github.com/matkuki/81ccd4114fee44f9494be4a0857fd7aa 
Download all three into a directory and change the Nim **lib** directory in the **setup.py** file to the one on your system, then just run
```sh
python3 build.py
```
and it should compile the Nim module and test it with Python 3. If it writes **SUCCESS** at the end then the module works, otherwise you'll get some **SIGABRT** error. 

If you have more than one Python 3 interpreter on the system, just change the commands in **build.py** from **python3** to **python3.6**, if you are using Python 3.6.
The weird thing is this exact same code works on Windows and I tried it with multiple versions of Python 3.

Thanks for the help!

**Comment by jasonrbriggs** [comment]
Got an error compiling the nim module until I added a discard on line 133. After that compiled and ran but with the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: initialization of nim_module failed without raising an exception
```

**Comment by matkuki** [comment]
That's great! It got farther than on the Raspberry PI (Ubuntu Mate), which throws a memory error on line 132!
So you changed line 133 to:
```nim
discard moduleCreate(addr(nim_module))
```
or just:
```nim
discard
```
Can you give me the error message when compiling line 133 without any changes?

Thanks!

**Comment by matkuki** [comment]
I'm closing this issue.

Thanks.

**Comment by jasonrbriggs** [comment]
Sorry, i'm not getting regular github notifications.

I changed it to:

```
discard moduleCreate(addr(nim_module))
```

(in terms of the original issue, good to close anyway... thanks)

**Comment by matkuki** [comment]
Thanks @jasonrbriggs !

Could you change the lines:
```nim
proc PyInit_nim_module() {.exportc, cdecl.} =
    {.emit: """NimMain();""".}
    initialize()
    discard moduleCreate(addr(nim_module))
```
to:
```nim
proc PyInit_nim_module(): PyObjectPtr {.exportc, cdecl.} =
    {.emit: """NimMain();""".}
    initialize()
    result = moduleCreate(addr(nim_module))
```
and try it? Note the added return type to the procedure!

**Comment by jasonrbriggs** [comment]
Woot!

```
$ python build.py
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: system [Processing]
Hint: nim_module [Processing]
Hint: operation successful (10668 lines compiled; 0.085 sec total; 16.035MiB; Debug Build) [SuccessX]
running build_ext
SUCCESS
```

**Comment by matkuki** [comment]
Great!!!! 
Then the ARM architecture is the problem? Or maybe Ubuntu?

Thanks for all the help @jasonrbriggs !

**Comment by matkuki** [comment]
Hey @jasonrbriggs ,
Can you tell me what architecture your OS is? x64 or x86?
Also could you post the **nim_module.h** and **nim_module.c** that were created in the **nimcache** subdirectory inside where you compiled the example?

Thanks

**Comment by jasonrbriggs** [comment]
Both:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
```

Requested files attached to this gist: https://gist.github.com/jasonrbriggs/08ae17d7fba991619ed5d3c7d6016e53

**Comment by matkuki** [comment]
Thanks!
